apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::831574738468:user/github-ci
      username: github-ci
      groups:
        - system:masters
    - userarn: arn:aws:iam::831574738468:role/github-actions-role
      username: github-actions-role
      groups:
        - system:masters