name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20.5
        id: go

      - name: Check out code into the Go module directory
          uses: actions/checkout@v3

      - name: Test
          uses: make test